name: Deploy Theme

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.3
      with:
        node-version: 12.x

    - name: Install SASS Compiler
      run: npm install -g sass 

    - name: Compile SCSS Files
      run: sass scss/style.scss style.css

    - name: Delete Redundant Files
      run: rm -rf scss .git .github *.md .gitignore
    
    - name: Upload to English Site
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: "public_html/wp-content/themes/mtrcn/"

    - name: Upload to Turkish Site
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: "tr/wp-content/themes/mtrcn/"
